name = "erdetsnartlordag-counter"
main = "src/index.js"
compatibility_date = "2025-05-01"

# Run `npx wrangler kv namespace create COUNTER` and paste the returned id below.
[[kv_namespaces]]
binding = "COUNTER"
id = "ac5e956c3c7a452ab5ad2eeb67434234"
